/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module initialise_col_LED_6 (
    input [15:0] col0,
    input [15:0] col1,
    input [15:0] col2,
    input [15:0] col3,
    input [15:0] col4,
    input [15:0] col5,
    output reg [167:0] col0_led,
    output reg [167:0] col1_led,
    output reg [167:0] col2_led,
    output reg [167:0] col3_led,
    output reg [167:0] col4_led,
    output reg [167:0] col5_led
  );
  
  
  
  integer i;
  
  always @* begin
    col0_led = 168'h000000000000000000000000000000000000000000;
    col1_led = 168'h000000000000000000000000000000000000000000;
    col2_led = 168'h000000000000000000000000000000000000000000;
    col3_led = 168'h000000000000000000000000000000000000000000;
    col4_led = 168'h000000000000000000000000000000000000000000;
    col5_led = 168'h000000000000000000000000000000000000000000;
    for (i = 1'h0; i < 3'h7; i = i + 1) begin
      if (col0[(i)*1+0-:1] == 1'h1) begin
        col0_led[(i)*24+23-:24] = 24'hff0000;
      end else begin
        col0_led[(i)*24+23-:24] = 24'h000000;
      end
    end
    for (i = 1'h0; i < 3'h7; i = i + 1) begin
      if (col1[(i)*1+0-:1] == 1'h1) begin
        col1_led[(i)*24+23-:24] = 24'hff0000;
      end else begin
        col1_led[(i)*24+23-:24] = 24'h000000;
      end
    end
    for (i = 1'h0; i < 3'h7; i = i + 1) begin
      if (col2[(i)*1+0-:1] == 1'h1) begin
        col2_led[(i)*24+23-:24] = 24'hff0000;
      end else begin
        col2_led[(i)*24+23-:24] = 24'h000000;
      end
    end
    for (i = 1'h0; i < 3'h7; i = i + 1) begin
      if (col3[(i)*1+0-:1] == 1'h1) begin
        col3_led[(i)*24+23-:24] = 24'hff0000;
      end else begin
        col3_led[(i)*24+23-:24] = 24'h000000;
      end
    end
    for (i = 1'h0; i < 3'h7; i = i + 1) begin
      if (col4[(i)*1+0-:1] == 1'h1) begin
        col4_led[(i)*24+23-:24] = 24'hff0000;
      end else begin
        col4_led[(i)*24+23-:24] = 24'h000000;
      end
    end
    for (i = 1'h0; i < 3'h7; i = i + 1) begin
      if (col5[(i)*1+0-:1] == 1'h1) begin
        col5_led[(i)*24+23-:24] = 24'hff0000;
      end else begin
        col5_led[(i)*24+23-:24] = 24'h000000;
      end
    end
  end
endmodule
